version: '3'
services:
  # To run several containers in parallel use scale argument:
  # docker-compose up --build --scale attacker=5
  attacker:
    build: .
    restart: always
    environment:
      ATTACKER_THREADS: 500
      #ATTACKER_TARGET: https://kremlin.ru # Target one certain domain.
