version: "3.7"
services:
  ship:
    build:
      dockerfile: Dockerfile
      context: .
    image: fuckyourussianship
    restart: unless-stopped
    network_mode: host
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
