version: '3'
services:
  # To run several containers in parallel use scale argument:
  # docker-compose up --build --scale attacker=5
  attacker:
    build: .
    restart: always
    network_mode: host
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

    environment:
      # Defines the number of threads used in the script.
      ATTACKER_THREADS: 500
      #http_proxy: socks5://localhost:9050
      #https_proxy: socks5://localhost:9050

      # Defines target sites that will be used instead of a dynamic list of
      # sites retrieved by API.
      # NOTE: JSON should be valid.
      #ATTACKER_TARGETS: '["https://kremlin.ru", "https://sberbank.com"]'
