version: "3.3"
services:
  ship:
    build:
      dockerfile: Dockerfile
      context: .
    image: fuckyourussianship
#    Local TOR
    environment:
      - http_proxy=socks5://192.168.1.2:9050
      - https_proxy=socks5://192.168.1.2:9050
    restart: unless-stopped
    network_mode: host
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
